import { OrderIntent } from '@domain';
import { TradeFill } from '../engine/types';

/**
 * Decision log entry - records when an agent makes a decision
 */
export interface DecisionLog {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp of decision */
  timestamp: string;
  /** Order intents generated by the decision */
  intents: OrderIntent[];
  /** Number of intents that were filled */
  filledCount: number;
  /** Number of intents that were rejected */
  rejectedCount: number;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Trade log entry - records a filled trade with explainability fields
 */
export interface TradeLog {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp of trade */
  timestamp: string;
  /** Trade fill data */
  fill: TradeFill;
  /** Reason for the order (from OrderIntent) */
  reason?: string;
  /** Model's probability estimate (0 to 100) */
  modelProb?: number;
  /** Market's implied probability (0 to 100) */
  marketProb?: number;
  /** Calculated edge percentage */
  edgePct?: number;
  /** Stake as percentage of bankroll */
  stakePct?: number;
}

/**
 * Equity entry - records agent equity at a point in time
 */
export interface EquityEntry {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp */
  timestamp: string;
  /** Equity value (bankroll + unrealized PnL) */
  equity: number;
  /** Bankroll at this point */
  bankroll: number;
  /** Total PnL */
  pnlTotal: number;
}

